AllCops:
  TargetRubyVersion: "2.4"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false