version: 2
jobs:
  build:
    working_directory: ~/pswd
    docker:
      - image: circleci/ruby:2.4.2-node
    steps:
      - checkout

      - restore_cache:
        keys:
          - gems-{{ checksum "Gemfile.lock" }}
          - gems-

      - run:
        name: install dependencies
        command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
        key: gems-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
        name: Rubocop style check
        command: bundle exec rubocop

      - run:
        name: run tests
        command: |
          bundle exec rspec --profile 10 \
                            --format progress